export const queryKeys = {
  EVENTS: {
    CREATE_EVENT_MUTATION_KEY: 'CREATE_EVENT_MUTATION_KEY',
    EVENT_QUERY_KEY: 'EVENT_QUERY_KEY',
  },
  USER: {
    CREATE_USER_MUTATION_KEY: 'CREATE_USER_MUTATION_KEY',
    EVENT_IDS_QUERY_KEY: 'EVENT_IDS_QUERY_KEY',
  },
};
